version: '3.9'

services:
  invoice-ocr-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: invoice-ocr-api:latest
    container_name: invoice-ocr-api
    restart: unless-stopped
    ports:
      - "5100:5100"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PORT=5100
      - PYTHONUNBUFFERED=1
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY:-}
      - AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME:-gpt-4o}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-08-01-preview}
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5100/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G


