name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff
      - name: Lint (ruff)
        run: |
          ruff check . || true
      - name: Import check
        run: |
          python -c "import importlib;import sys;mods=['src.ocr_extractor','src.pdf_converter','src.ocr_service','src.pdf_service','src.zip_service'];[importlib.import_module(m) for m in mods];print('Imports OK')"


